name: Deploy to cloud

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: doadmin
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 25060:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
      
#     - name: Run Tests
#       env:
#         DB_HOST: localhost
#         DB_PASSWORD: postgres
#       run: |
#         gem install bundler
#         bundle install
#         bundle exec rake db:create RACK_ENV=test
#         bundle exec rake db:migrate RACK_ENV=test
#         bundle exec rake test
    - name: (Service) Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.FRONTEND_HOST }}
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.FRONTEND_SSHKEY }}
      with:
        source: "."
        target: "/home/rails/mq-worker"

    - name: (Service) Bundle and restart app server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FRONTEND_HOST }}
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.FRONTEND_SSHKEY }}
        script: |
          su - rails -c "cd /home/rails/mq-worker && bundle"
          sudo systemctl restart mq-worker.service
    - name: (Service API) Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.API_HOST }}
          USERNAME: root
          PORT: 22
          KEY: ${{ secrets.API_SSHKEY }}
        with:
          source: "."
          target: "/home/rails/mq-worker"

    - name: (Service API) Bundle and restart app server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.API_HOST }}
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.API_SSHKEY }}
        script: |
          su - rails -c "cd /home/rails/mq-worker && bundle"
          sudo systemctl restart mq-worker.service
